### PR TITLE
[CRM457-1778] Onboard additional providers (TRANCHE 10)

### PR DESCRIPTION
**Pull request by elken**
## Description of change

Merge on Monday 5th of August

[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1778)

### CODE REVIEW

**Review by jogilder — CHANGES_REQUESTED** [review]
@elken this list of office codes is the one for 29/07/2024 not the ones from tranche 10

**Comment by elken** [comment]
> @elken this list of office codes is the one for 29/07/2024 not the ones from tranche 10

Resolved

**Comment by elken** [comment]
This is blocked by Snyk issues for now, looks like they're being solved as part of #1033

**Review by jogilder — APPROVED** [review]
LGTM

**Pull request merged**
